pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'docker-demo:$(Build.BuildId)'
  dockerId : 'test'

steps:
- script: docker build -f DockerDemo/Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
  workingDirectory: src/
  displayName: 'Docker Build'

